# -*- coding: utf-8 -*-
"""Adivinhacao

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UMgLfO7U9NfozWodmOPsMGDqAyGAMvwa
"""

from random import randint

print("----- Iniciando o Super Game -----")

tesouro = randint(0,100)
chute = 0
chances = 10

while chute != tesouro:
  chute = input("Qual numero voce acha que é?)")
  if chute.isnumeric():
    chute = int(chute)
    chances = chances - 1
    if chute == tesouro:
      print('')
      print('Acertou, o loco meu, brincadeira..Quem sabe faz ao vivo!!!')
      print('O numero era {} e voce ainda tinha {} chances'.format(tesouro,chances))
      print('')
      break;
    else:
      print('')
      if chute > tesouro:
        print('Errrou! Dica: É um numero menor!')
      else:
        print('Errrou! Dica: É um numero maior')
        print('Voce ainda possui {} chances'.format(chances))
    if chances == 0:
      print('')
      print(f'Suas chances acabaram. O numero era: {tesouro}. Voce Perdeu!')
      print('')
      break;
  else:
    print('')
    print('Voce inseriu letras, é apenas numeros')
    print(f'Voice ainda possui {chances} chances')
    print('')      
print("----- Game Over -----")